### ISSUE TITLE
why I cannot install this

### ISSUE THREAD

**Issue by thereishander** [drvinaayaksingh/swisseph#3]
the package-lock.json seems do not work on  my computer,then,I use "npm install " to rebuild it but it don't work 
![1](https://github.com/user-attachments/assets/4ffc5486-c331-4e6c-9096-c230249b820e)
this is my npm version and settings
![2](https://github.com/user-attachments/assets/448af4b7-4d4e-4aef-9e83-d71e0750c04b)

**Comment by roabhi** [comment]
I am having a similar problem on Linux. I assume it is related with the python version of the OS and node-gyp. I am posting my error here 

`npm error code 1
npm error path /home/rob/Environment/astro-app-api/node_modules/swisseph-v2
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@20.16.0 | linux | x64
npm error gyp info find Python using Python version 3.12.4 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/rob/Environment/astro-app-api/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/rob/Environment/astro-app-api/node_modules/swisseph-v2/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/rob/Environment/astro-app-api/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/rob/.cache/node-gyp/20.16.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/rob/.cache/node-gyp/20.16.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/rob/Environment/astro-app-api/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/rob/.cache/node-gyp/20.16.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/rob/Environment/astro-app-api/node_modules/swisseph-v2',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: not found: make
npm error gyp ERR! stack at getNotFoundError (/home/rob/Environment/astro-app-api/node_modules/which/lib/index.js:16:17)
npm error gyp ERR! stack at which (/home/rob/Environment/astro-app-api/node_modules/which/lib/index.js:77:9)
npm error gyp ERR! stack at async doWhich (/home/rob/Environment/astro-app-api/node_modules/node-gyp/lib/build.js:119:22)
npm error gyp ERR! stack at async loadConfigGypi (/home/rob/Environment/astro-app-api/node_modules/node-gyp/lib/build.js:78:7)
npm error gyp ERR! stack at async build (/home/rob/Environment/astro-app-api/node_modules/node-gyp/lib/build.js:36:3)
npm error gyp ERR! stack at async run (/home/rob/Environment/astro-app-api/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 6.9.12-3-MANJARO
npm error gyp ERR! command "/home/rob/.nvm/versions/node/v20.16.0/bin/node" "/home/rob/Environment/astro-app-api/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /home/rob/Environment/astro-app-api/node_modules/swisseph-v2
npm error gyp ERR! node -v v20.16.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok`


If the creator of the repo could share some light it would be greatly appreciated

**Comment by drvinaayaksingh** [comment]
Try with node version 20. Have updated the package to use node 20.
